-- The labelled dataset. 46 applications, each with the decision a human
-- actually wants, which is not always the decision the current thresholds
-- produce.
--
-- Read that sentence again, because it is the whole reason this file exists.
-- If the labels were generated by running the rules, the eval would score
-- 100% every time, would stay at 100% through any change, and would be a
-- workflow that prints a number rather than a test. Every label here is a
-- judgement, and the seven rows marked DISAGREES are ones where the judgement
-- and the rules differ on purpose.
--
-- Those seven are what the accuracy number is measuring. The score is not
-- meant to reach 1.0 -- a rule set that agrees with a human on every edge
-- case does not exist, and chasing it produces thresholds overfitted to 46
-- rows. It is meant to move in the right direction when you change a
-- threshold, and to tell you what you broke when it does not.
--
--   psql "$DATABASE_URL" -f n8n/sql/02-golden-set.sql
--
-- Re-runnable: ON CONFLICT DO UPDATE, so fixing a label is editing this file
-- and running it again rather than a hand-written UPDATE nobody records.

INSERT INTO golden_set
    (external_id, email, handle, platform, followers, expected_decision, note)
VALUES

-- --- clearly above the bar ------------------------------------------------
('g-001', 'ana@example.com',    'anacooks',     'youtube',   142000, 'accepted', 'large, on topic'),
('g-002', 'ben@example.com',    'benbuilds',    'tiktok',     88000, 'accepted', 'large'),
('g-003', 'cara@example.com',   'caradraws',    'instagram',  51000, 'accepted', 'large'),
('g-004', 'dan@example.com',    'danlifts',     'youtube',    34000, 'accepted', 'comfortably above'),
('g-005', 'eve@example.com',    'evetravels',   'tiktok',     20000, 'accepted', 'exactly on the accept threshold'),
('g-006', 'finn@example.com',   'finnfixes',    'youtube',   910000, 'accepted', 'very large'),
('g-007', 'gia@example.com',    'giagames',     'tiktok',     26500, 'accepted', 'large'),
('g-008', 'hugo@example.com',   'hugohikes',    'instagram',  22300, 'accepted', 'just above'),

-- --- the band where a human should look -----------------------------------
('g-009', 'iris@example.com',   'irisinks',     'youtube',    19999, 'review',   'one follower below the accept threshold'),
('g-010', 'jack@example.com',   'jackjams',     'tiktok',     12000, 'review',   'mid band'),
('g-011', 'kim@example.com',    'kimknits',     'instagram',   8200, 'review',   'mid band'),
('g-012', 'leo@example.com',    'leolearns',    'youtube',     5000, 'review',   'exactly on the review threshold'),
('g-013', 'mia@example.com',    'miamakes',     'tiktok',      6400, 'review',   'mid band'),
('g-014', 'nia@example.com',    'niaknows',     'youtube',    15750, 'review',   'mid band'),
('g-015', 'omar@example.com',   'omarowns',     'instagram',  11100, 'review',   'mid band'),

-- --- clearly below the bar ------------------------------------------------
('g-016', 'pia@example.com',    'piapaints',    'youtube',     4999, 'rejected', 'one follower below the review threshold'),
('g-017', 'quin@example.com',   'quinquilts',   'tiktok',      1200, 'rejected', 'small'),
('g-018', 'rosa@example.com',   'rosaruns',     'instagram',     84, 'rejected', 'small'),
('g-019', 'sam@example.com',    'samsings',     'youtube',        0, 'rejected', 'no audience'),
('g-020', 'tara@example.com',   'taratalks',    'tiktok',       310, 'rejected', 'small'),
('g-021', 'uma@example.com',    'umaunboxes',   'instagram',   2450, 'rejected', 'small'),
('g-022', 'vik@example.com',    'vikvlogs',     'youtube',     4100, 'rejected', 'small'),

-- --- malformed: the pipeline must reject these before they reach a table --
('g-023', 'not-an-email',       'wesworks',     'youtube',    30000, 'invalid',  'email has no @'),
('g-024', 'xena@example.com',   'xenaxplores',  'twitch',     45000, 'invalid',  'platform is not one we can track'),
('g-025', 'yuri@example.com',   'yuriyells',    'linkedin',   60000, 'invalid',  'platform is not one we can track'),
('g-026', 'zoe@example.com',    'zoezooms',     'youtube',      NULL, 'invalid',  'followers missing'),
('g-027', 'ada@example.com',    '',             'tiktok',     18000, 'invalid',  'handle is empty'),
('g-028', '',                   'bobbakes',     'instagram',  25000, 'invalid',  'email is empty'),
('g-029', 'cy@example.com',     'cycycles',     'youtube',       -5, 'invalid',  'negative followers'),
('g-030', 'dee@example.com',    'deedances',    'YOUTUBE',    41000, 'accepted', 'uppercase platform normalises, not an error'),
('g-031', 'eli@example.com',    '@eliedits',    'tiktok',     33000, 'accepted', 'leading @ is stripped, not an error'),
('g-032', 'fay@example.com',    'faysews',      ' instagram ', 27000, 'accepted', 'whitespace normalises, not an error'),

-- --- rows where the rules and the human disagree --------------------------
-- These seven are the point of the file. Each one is a case where follower
-- count alone gives the wrong answer, and each names the signal the rules
-- cannot see. When somebody proposes a new threshold, this is the set that
-- says whether the proposal helps or just moves the mistakes around.
('g-033', 'gus@example.com',    'gusgrills',    'youtube',     4200, 'review',   'DISAGREES: rules reject. 4.2k but a niche BBQ audience with very high engagement'),
('g-034', 'hana@example.com',   'hanahacks',    'tiktok',      3100, 'review',   'DISAGREES: rules reject. 3.1k and already posting about us unpaid'),
('g-035', 'ivan@example.com',   'ivanbot',      'instagram',  95000, 'rejected', 'DISAGREES: rules accept. 95k followers, engagement says the audience is bought'),
('g-036', 'jo@example.com',     'joreposts',    'tiktok',     64000, 'rejected', 'DISAGREES: rules accept. large but reposts other people work'),
('g-037', 'kai@example.com',    'kaikitchen',   'youtube',    21000, 'review',   'DISAGREES: rules accept. just over the line and brand new account'),
('g-038', 'lena@example.com',   'lenalens',     'instagram',  17800, 'accepted', 'DISAGREES: rules review. under the line but a repeat partner from last year'),
('g-039', 'max@example.com',    'maxmods',      'youtube',     9500, 'accepted', 'DISAGREES: rules review. under the line but the exact audience the programme targets'),

-- --- boundaries worth keeping a row for -----------------------------------
-- Off-by-one bugs live at thresholds, and a threshold with no test either
-- side of it is a threshold nobody has checked.
('g-040', 'nora@example.com',   'norareads',    'tiktok',      5001, 'review',   'one above the review threshold'),
('g-041', 'otis@example.com',   'otisoutdoors', 'youtube',    20001, 'accepted', 'one above the accept threshold'),
('g-042', 'pam@example.com',    'pampots',      'instagram',      1, 'rejected', 'one follower'),
('g-043', 'raj@example.com',    'rajrides',     'youtube',  1000000000, 'accepted', 'implausibly large but not malformed'),
('g-044', 'sara@example.com',   'sarasolders',  'tiktok',     19998, 'review',   'two below the accept threshold'),
('g-045', 'tom@example.com',    'tomtunes',     'instagram',   4998, 'rejected', 'two below the review threshold'),
('g-046', 'ugo@example.com',    'ugougc',       'youtube',    20000, 'accepted', 'duplicate of the threshold case, different platform')

ON CONFLICT (external_id) DO UPDATE SET
    email             = EXCLUDED.email,
    handle            = EXCLUDED.handle,
    platform          = EXCLUDED.platform,
    followers         = EXCLUDED.followers,
    expected_decision = EXCLUDED.expected_decision,
    note              = EXCLUDED.note,
    labelled_at       = now();
