-- Interview practice: every case the simulator writes, the questions asked
-- about it, the answer given and the feedback on that answer.
--
--   psql "$DATABASE_URL" -f n8n/sql/03-prep.sql
--
-- Idempotent: every statement is IF NOT EXISTS, so re-running it is safe.

BEGIN;

-- The id is generated by the page when it renders the button, not by the
-- database. Clicking twice sends the same id, so it is one case, and one
-- call to the model, rather than two.
CREATE TABLE IF NOT EXISTS prep_attempts (
    id          uuid        PRIMARY KEY,
    kind        text        NOT NULL
                CHECK (kind IN ('decomposition', 'screening', 'patterns')),
    title       text        NOT NULL,
    -- context, client_ask, hidden_facts, evaluation
    brief       jsonb       NOT NULL,
    -- [{ q, a }]: clarifying questions and the client's replies, in order
    transcript  jsonb       NOT NULL DEFAULT '[]'::jsonb,
    answer      text,
    feedback    jsonb,
    model       text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    answered_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_prep_attempts_recent
    ON prep_attempts (created_at DESC);

COMMIT;
