"""Embed the pages into the workflows that serve them.

    python n8n/dashboard/build.py

Each page is a normal HTML file so it can be edited and previewed in a browser.
n8n needs it as a JavaScript string inside a Code node; this script writes that
string. The test suite fails if a committed workflow is out of date.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAGE = HERE / "page.html"
WORKFLOW = HERE.parent / "workflows" / "04-dashboard.json"
PREP_PAGE = HERE.parent / "prep" / "page.html"
PREP_WORKFLOW = HERE.parent / "workflows" / "05-prep.json"
FAKE_PAGE = HERE.parent / "fake" / "page.html"
FAKE_WORKFLOW = HERE.parent / "workflows" / "99-fake-providers.json"
TARGETS = [(PAGE, WORKFLOW), (PREP_PAGE, PREP_WORKFLOW), (FAKE_PAGE, FAKE_WORKFLOW)]
NODE = "Render the page"
PLACEHOLDER = "/*__STATE__*/null"

# Non-ASCII characters in these strings are written as escapes, never typed:
# a literal U+2028 looks like a space in an editor.
JS_HEAD = r"""// Put the live state into the page and return it as HTML.
//
// Generated by n8n/dashboard/build.py from n8n/dashboard/page.html. Edit the
// page and rebuild; do not edit the template string by hand.
//
// The JSON is escaped for a <script> element, because handles and error
// messages come from outside and "</script>" in one would end the block.
// The replacement is a function, because a replacement string would read
// "$'" inside the data as a pattern.
"""

JS_TAIL = r"""
const state = $input.first().json.state ?? {};
const json = JSON.stringify(state)
  .replace(/</g, '\\u003c')
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029');

if (!TEMPLATE.includes('/*__STATE__*/null')) {
  throw new Error('dashboard template has no state placeholder');
}

return [{ json: { html: TEMPLATE.replace('/*__STATE__*/null', () => json) } }];"""


def render_js(page: str) -> str:
    return JS_HEAD + "\nconst TEMPLATE = " + json.dumps(page, ensure_ascii=False) + ";\n" + JS_TAIL


def embed(page_path: Path, workflow_path: Path) -> None:
    page = page_path.read_text(encoding="utf-8")
    if PLACEHOLDER not in page:
        raise SystemExit(f"{page_path} has no {PLACEHOLDER} placeholder")

    wf = json.loads(workflow_path.read_text(encoding="utf-8"))
    nodes = [n for n in wf["nodes"] if n["name"] == NODE]
    if len(nodes) != 1:
        raise SystemExit(f"expected exactly one node named {NODE!r} in {workflow_path.name}, found {len(nodes)}")

    nodes[0]["parameters"]["jsCode"] = render_js(page)
    workflow_path.write_text(json.dumps(wf, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"embedded {page_path.parent.name}/{page_path.name} ({len(page):,} chars) into {workflow_path.name}")


def main() -> None:
    for page_path, workflow_path in TARGETS:
        embed(page_path, workflow_path)


if __name__ == "__main__":
    main()
