"""Embed page.html into the dashboard workflow.

    python n8n/dashboard/build.py

The page is a normal HTML file so it can be edited and previewed in a browser.
n8n needs it as a JavaScript string inside a Code node; this script writes that
string. The test suite fails if the committed workflow is out of date.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAGE = HERE / "page.html"
WORKFLOW = HERE.parent / "workflows" / "04-dashboard.json"
NODE = "Render the page"
PLACEHOLDER = "/*__STATE__*/null"

# Non-ASCII characters in these strings are written as escapes, never typed:
# a literal U+2028 looks like a space in an editor.
JS_HEAD = r"""// Put the live state into the page and return it as HTML.
//
// Generated by n8n/dashboard/build.py from n8n/dashboard/page.html. Edit the
// page and rebuild; do not edit the template string by hand.
//
// The JSON is escaped for a <script> element, because handles and error
// messages come from outside and "</script>" in one would end the block.
// The replacement is a function, because a replacement string would read
// "$'" inside the data as a pattern.
"""

JS_TAIL = r"""
const state = $input.first().json.state ?? {};
const json = JSON.stringify(state)
  .replace(/</g, '\\u003c')
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029');

if (!TEMPLATE.includes('/*__STATE__*/null')) {
  throw new Error('dashboard template has no state placeholder');
}

return [{ json: { html: TEMPLATE.replace('/*__STATE__*/null', () => json) } }];"""


def render_js(page: str) -> str:
    return JS_HEAD + "\nconst TEMPLATE = " + json.dumps(page, ensure_ascii=False) + ";\n" + JS_TAIL


def main() -> None:
    page = PAGE.read_text(encoding="utf-8")
    if PLACEHOLDER not in page:
        raise SystemExit(f"{PAGE.name} has no {PLACEHOLDER} placeholder")

    wf = json.loads(WORKFLOW.read_text(encoding="utf-8"))
    nodes = [n for n in wf["nodes"] if n["name"] == NODE]
    if len(nodes) != 1:
        raise SystemExit(f"expected exactly one node named {NODE!r}, found {len(nodes)}")

    nodes[0]["parameters"]["jsCode"] = render_js(page)
    WORKFLOW.write_text(json.dumps(wf, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"embedded {PAGE.name} ({len(page):,} chars) into {WORKFLOW.name}")


if __name__ == "__main__":
    main()
