"""Embed page.html into the dashboard workflow.

    python n8n/dashboard/build.py

The page is written as a normal HTML file so it can be edited, previewed in a
browser and diffed like one. n8n needs it inside a Code node as a JavaScript
string, which is unreadable and unreviewable. This script is the bridge, and
it is the only thing allowed to write that string.

The generated workflow is committed, so deploying never needs this script to
run. The test suite checks that the committed workflow matches page.html byte
for byte; editing the page and forgetting to rebuild fails CI instead of
shipping yesterday's dashboard.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAGE = HERE / "page.html"
WORKFLOW = HERE.parent / "workflows" / "07-dashboard.json"
NODE = "Render the page"
PLACEHOLDER = "/*__STATE__*/null"

# The Code node around the template. Kept here rather than in the workflow so
# the one piece of logic that touches untrusted data is readable in a diff.
#
# Every non-ASCII character in these two strings is written as an escape, never
# typed. U+2028 renders as whitespace in an editor, and an earlier draft of
# this file replaced every ordinary space in the page data with a line
# separator because the one in the regex was a space that looked identical.
JS_HEAD = r"""// Put the live state into the page and hand it back as HTML.
//
// Generated by n8n/dashboard/build.py from n8n/dashboard/page.html. Do not
// edit the template string below by hand: edit page.html and rebuild.
//
// Two details here are security, not style.
//
// The JSON is escaped for embedding inside a <script> element. Applicant
// handles, notes and error messages all come from outside, and a value
// containing </script> would otherwise end the script block and let the rest
// of the string run as markup. Escaping every < as \u003c keeps it inside the
// JSON literal. U+2028 and U+2029 are escaped too, because older engines
// treat them as line breaks inside a string literal.
//
// The replacement is a function, not a string. String.prototype.replace reads
// $& and $' in a replacement string as patterns, so an error message
// containing "$'" would splice part of the template into the data.
"""

JS_TAIL = r"""
const state = $input.first().json.state ?? {};
const json = JSON.stringify(state)
  .replace(/</g, '\\u003c')
  .replace(/\u2028/g, '\\u2028')
  .replace(/\u2029/g, '\\u2029');

if (!TEMPLATE.includes('/*__STATE__*/null')) {
  throw new Error('dashboard template has no state placeholder');
}

return [{ json: { html: TEMPLATE.replace('/*__STATE__*/null', () => json) } }];"""


def render_js(page: str) -> str:
    return JS_HEAD + "\nconst TEMPLATE = " + json.dumps(page, ensure_ascii=False) + ";\n" + JS_TAIL


def main() -> None:
    page = PAGE.read_text(encoding="utf-8")
    if PLACEHOLDER not in page:
        raise SystemExit(f"{PAGE.name} has no {PLACEHOLDER} placeholder")

    wf = json.loads(WORKFLOW.read_text(encoding="utf-8"))
    nodes = [n for n in wf["nodes"] if n["name"] == NODE]
    if len(nodes) != 1:
        raise SystemExit(f"expected exactly one node named {NODE!r}, found {len(nodes)}")

    nodes[0]["parameters"]["jsCode"] = render_js(page)
    WORKFLOW.write_text(json.dumps(wf, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"embedded {PAGE.name} ({len(page):,} chars) into {WORKFLOW.name}")


if __name__ == "__main__":
    main()
